###
GET https://localhost:7298/swagger


#Get pulando 5 e pegando 10 itens
###
GET https://localhost:7298/filme?skip=5&take=10

#Get sem parametro
###
GET https://localhost:7298/filme

#Get pegando id 3
###
GET https://localhost:7298/filme/3

###
POST https://localhost:7298/filme
Content-Type: application/json

{
    "Titulo": "Avataz",
    "Genero": "Ação",
    "Duracao": 150
}

#Atualiza nome do filme, do ID 8
###
PATCH https://localhost:7298/filme/8
Content-Type: application/json

[
    {
        "op": "replace",
        "path": "/titulo",
        "value": "Avatar"
    }
]

###
DELETE https://localhost:7298/filme/8